""""
Módulo Collections - Counter (contador)
https://docs.python.org/3/library/collections.html#collections.Counter

colections = high-performance container datetypes

Counter = recebe um interavel como parametro e cria um objeto do tipo Collections Counter que é parecido
com um dicionario, contendo como chave o elemento da lista passada como parametro e como valor a quantidade
de ocorrencias desse elemento.
* É nessessario realizar o importamento da biblioteca para utilizar
---------------------------------------------------------------------------------------
# Realizando o Import
from collections import Counter

# exemplo 1
# podemos utilizar qualquer interavel aqui usamos uma lista

lista = [1, 2, 3, 1, 3, 4, 2, 1, 3, 5, 4, 5, 4, 42, 42, 99]

# utilizamos o Counter
res = Counter(lista)

print(type(res))
print(res)
------------------------------------------------------------
# Realizando o Import
from collections import Counter

# exemplo 2

print(Counter('vai tomar no meio do seu cu seu filho de uma puta arrombada '))

"""
# Realizando o Import
from collections import Counter

# exemplo 3

texto = """" Ele está acompanhado. Seus olhos percorrem meu corpo. Ele me come com o olhar!
 As pessoas ao redor parecem não notar, mas eu sei! Ele me quer! E ela também sabe. No fundo, acho que 
 ela me quer também...
Preciso me aproximar! Minha calcinha já não consegue mais conter a umidade.. Minhas coxas estão molhadas.
 Ele me quer... ela também...
Me aproximo e sussurro no ouvido dela que eu quero. Eu quero foder. Agora! Ela sorri, maliciosa.
Olhamos para ele e nos dirigimos ao quarto no andar superior. Eu e ela, ele nos segue. As pessoas ao redor
parecem não notar, mas eu sei! Ele me quer... ela também...
Ele fecha a porta atrás de nós. Eu enfio minha língua em sua boca. Ele senta e nos observa. 
Expõe seu sexo e com movimentos suaves e constantes, começa a se masturbar. Eu e ela em pé.
Percorro minhas mãos por todo seu corpo. Aperto e sua bunda, e por trás, enfio a mão em sua buceta... 
Ela me beija, me lambe, me roça... Ele assiste, extasiado...
Chego minha calcinha pro lado e fico de quatro na cama. Ordeno que ela me chupe... 
E ela chupa, com uma delicadeza, de uma maneira que só outra mulher sabe fazer...
Eu começo a gemer, e ela enfia seus dedos na minha buceta...
Olho pra trás, só vejo seus olhos...
e vejo ele... de pé, já nu.... o pau duro...
Não queria que ele metesse nela. Eu foderia os dois! Empurro ela na cama e começo a chupá-la,
oferecendo minha bunda pra ele penetrar... e quando ele entra em mim, eu mordo a coxa dela, tamanho tesão...
Parece um ballet, movimentos coordenados... Ele mete, eu chupo, ela geme.... Eu gozo... E me levanto... 
Ele não vai meter nela! Aqui, ele só mete em mim...
Deito ele na cama e cavalgo sobre seu pau, de costas. Ele aperta bate na minha bunda com força... 
Quanto mais bate, mais excitada eu fico... Ela chupa meus peitos enquanto sento no seu homem... 
Enfio dois dedos na sua buceta molhada, e ela geme de prazer.... Ele me quer... ela também...
Gozo de novo... ela goza nos meus dedos! Caímos lado a lado na cama, nos beijando... 
Ele olha, e nos oferece seu o pau para ser chupado... A gente se beija, com o pau dele no meio... 
As línguas se entrelaçam enquanto, ajoelhadas a sua frente, lambemos a cabeça com suavidade... 
eu engulo ele inteiro, e depois ofereço pra ela engolir também... 
e continuamos nessa troca, até ele quase explodir...
Mas não, ele não ia gozar ali... ele vai gozar em mim... levanto em me encaixo em seu corpo, 
entrelaçando minhas pernas ao seu redor. Ele levanta e me sustenta no sobe e desce, dentro de mim, 
me segurando pelas pernas... é a vez dela olhar seu homem me comer...
Desço e me debruço na janela, novamente oferecendo minha bunda pra ele... 
Ela corre e se ajoelha a minha frente para chupar meu clitóris enquanto ele me penetra... 
É o máximo do prazer... Quatro mãos, duas bocas, inúmeros toques, um pau.... 
Gozo novamente quando sinto sua porra jorrar dentro de mim... E ela, ajoelhada, lambe nosso prazer...
Exaustos, nos rendemos ao cansaço, e deitamos entrelaçados, eu no meio dos dois, 
para que pudéssemos recomeçar assim que nossos corpos permitissem... 
E no fundo, eu realmente tinha razão... Ele me quer... ela também..."""

palavras = texto.split()  # separa o texto em palavras para q o Counter nao separe letra por letra

res = Counter(palavras)

print(res)
# .most_common(n) retorna a quantidade de valores n dos elementos q mais se repetiram
print(res.most_common(5))

# se for no terminal do pycharme e importa o Counter e digitar help(Counter) aparece todas as imformações e formas
# utilizar o Counter